# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b86ee37389ef349337cfa22bb5b9fe65c19990c27deb6d9935d9df2a23c6af43449bc02e03b0e1a1f1340a7c5af303c7d5b2e718935e1480a9aaaf5dbcd325e3

test:
  secret_key_base: 60699a5ff0efa55672fbfaa6614ed837ef6397242a64b640431fab1780c8f6e3cec8504144d4a41db138e3398d476f6543a465ae0792608d8b9101b25bac177f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
